### PR TITLE
Cambios en el menu responsivo

### PR DESCRIPTION
**Pull request by Yuriine**
A

### CODE REVIEW

**Comment by kralion** [comment]
It has conflicts, please review, the final view looks like this, the conflict is in regard to the view of the '/products' route

[BlueMotors.com](https://bluemotors.netlify.app/productos)

**Comment by Yuriine** [comment]
no hay conflictos papi, pa que hora me revisas :v

**Comment by kralion** [comment]
My bad, **merged**

**Comment by kralion** [comment]
Is this a normal behavior ? I mean , maybe the bg for the sidebar should be black instead of transparentimage

**Pull request merged**
